### ISSUE TITLE
Logout navigates back to Login Screen in TabView

### ISSUE THREAD

**Issue by ameysunu** [ameysunu/realm-swiftui#20]
## Steps to Reproduce:

* Logout user from the `UserPage`.
* It navigates back to the LoginPage and logs out the user successfully, however still remains in the `TabView`

**Comment by arihantthriwe** [comment]
Please assign me this.

**Comment by arihantthriwe** [comment]
Hey how should i add the screen recording so that you can verify the issue i have solved.
