### ISSUE TITLE
Display an empty text label if data is empty

### ISSUE THREAD

**Issue by ameysunu** [ameysunu/realm-swiftui#22]
**Existing Scenario:**
* The main page is empty, shows no values when there is no data initially that is added

**Proposed Feature:**
* The page should show some text, saying that data is empty or an equivalent design for empty values.
* Let your creativity run wild here, with SwiftUI.

**Comment by arihantthriwe** [comment]
Hey, as this is a good first issue i would like to work on it. :)

**Comment by ameysunu** [comment]
> Hey, as this is a good first issue i would like to work on it. :)

Sure!
