### ISSUE TITLE
Launch screen and App Icon

### ISSUE THREAD

**Issue by arihant-dev** [ameysunu/realm-swiftui#26]
Add Launch Screen and App icon for the app.

**Comment by arihantthriwe** [comment]
Please assign me this.
@ameysunu 
:)

**Comment by ameysunu** [comment]
> Hey :)
> What should i name this app?

Hi! You can leave the name as it is, or have something like `RealmSwiftUI` such that the project remains abstract.

**Comment by arihantthriwe** [comment]
Ok Sure :)
